# Generated by Django 6.0.3 on 2026-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_ingredients_unit_alter_recipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество (гр или шт)'),
        ),
    ]
