# Generated by Django 6.0.3 on 2026-04-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_ingredients_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingridients/'),
        ),
    ]
