# Generated by Django 6.0.3 on 2026-04-11 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_ingredients_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'Предпочтение пользователя', 'verbose_name_plural': 'Предпочтения пользователей'},
        ),
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('user', 'ingredient')},
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=20, verbose_name='Цель')),
                ('target_calories', models.IntegerField(verbose_name='Целевые калории')),
                ('budget_mode', models.BooleanField(default=False, verbose_name='Эконом режим')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_saved', models.BooleanField(default=False, verbose_name='Сохранён')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'План питания',
                'verbose_name_plural': 'Планы питания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3, verbose_name='День')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], max_length=20, verbose_name='Тип приёма пищи')),
                ('portion', models.FloatField(default=1.0, verbose_name='Порция')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainapp.mealplan', verbose_name='План')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.recipes', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Приём пищи в плане',
                'verbose_name_plural': 'Приёмы пищи в плане',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_mode', models.BooleanField(default=False, verbose_name='Эконом режим')),
                ('default_goal', models.CharField(default='maintain', max_length=20, verbose_name='Цель по умолчанию')),
                ('default_calories', models.IntegerField(default=2000, verbose_name='Калории по умолчанию')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
