# Generated by Django 6.0.3 on 2026-04-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_userpreference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус'), ('any', 'Любой')], default='any', max_length=20, verbose_name='Тип приёма пищи'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
