# Generated by Django 6.0.3 on 2026-04-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_recipes_meal_type_alter_recipes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='goal_suitability',
            field=models.CharField(choices=[('lose', 'Похудение'), ('maintain', 'Поддержание'), ('gain', 'Набор массы'), ('any', 'Любая цель')], default='any', max_length=20, verbose_name='Подходит для цели'),
        ),
    ]
