# Generated by Django 6.0.3 on 2026-04-21 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_recipes_goal_suitability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='spoonacular_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID в Spoonacular'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'recipe')},
        ),
    ]
