# Generated by Django 5.2.11 on 2026-04-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_recipes_spoonacular_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='budget_mode',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='spoonacular_id',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='budget_mode',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='budget_tier',
            field=models.CharField(choices=[('economy', 'Эконом'), ('medium', 'Средний'), ('premium', 'Премиум')], default='medium', max_length=20, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='budget_tier',
            field=models.CharField(choices=[('economy', 'Эконом'), ('medium', 'Средний'), ('premium', 'Премиум')], default='medium', max_length=20, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='cookinghistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kitchenname',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mealplanitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
