# Generated by Django 5.2.11 on 2026-04-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_recipes_cost_level_alter_cookinghistory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='spoonacular_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID в Spoonacular'),
        ),
    ]
