# Generated by Django 6.0.3 on 2026-04-25
"""
Data migration: assign default images to recipes based on their names.
Maps recipe names to existing image files in media/recipes/.
"""

from django.db import migrations


# Mapping of recipe name keywords to image files
IMAGE_MAP = {
    'Бефстроганов': '11_Бутерброд_с_сыром.jpg',
    'Немецкий гуляш': '23_Гуляш_из_говядины_с_пюре.jpg',
    'Борщ с говядиной': '16_Борщ.jpg',
    'Венгерский суп': '21_Гороховый_суп.jpg',
    'Румынское рагу': '1_Борщ.jpg',
    'Борщ русский': '16_Борщ.jpg',
    'Овсянка': '6_Овсянка_на_молоке.jpg',
    'Яичница': '8_Омлет.jpg',
    'Омлет': '8_Омлет.jpg',
    'Творог со сметаной': '9_Творог_со_сметаной.jpg',
    'Блинчики': '8_Омлет.jpg',
    'Бутерброд с сыром': '11_Бутерброд_с_сыром.jpg',
    'Гречка с молоком': 'kasha_risovaya.png',
    'Куриное филе с рисом': '13_Куриное_филе_с_рисом.jpg',
    'Плов': '14_Плов_с_курицей.jpg',
    'Макароны по-флотски': '15_Макароны_по-флотски.jpg',
    'Борщ': '16_Борщ.jpg',
    'Куриный суп': '17_Куриный_суп.jpg',
    'Картофельное пюре': '18_Картофельное_пюре_с_котлетой.jpg',
    'Гречка с котлетой': '18_Картофельное_пюре_с_котлетой.jpg',
    'Рассольник': '17_Куриный_суп.jpg',
    'Гороховый суп': '21_Гороховый_суп.jpg',
    'Запечённая рыба': '27_Жаркое_из_свинины_с_картошкой.jpg',
    'Гуляш из говядины': '23_Гуляш_из_говядины_с_пюре.jpg',
    'Куриные котлеты': '34_Котлеты_по-киевски.jpg',
    'Тушёная капуста': '27_Жаркое_из_свинины_с_картошкой.jpg',
    'Рыбные котлеты': '34_Котлеты_по-киевски.jpg',
    'Жаркое': '27_Жаркое_из_свинины_с_картошкой.jpg',
    'Банановый смузи': '28_Банановый_смузи.jpg',
    'Салат из огурцов': '29_Салат_из_огурцов_и_помидоров.jpg',
    'Сырники': '30_Сырники.jpg',
    'Яблоко с творогом': '30_Сырники.jpg',
    'Бутерброд с ветчиной': '32_Бутерброд_с_ветчиной.jpg',
    'Пельмени': '14_Плов_с_курицей.jpg',
    'Котлеты по-киевски': '34_Котлеты_по-киевски.jpg',
    'Щи': '16_Борщ.jpg',
    'Каша рисовая': 'kasha_risovaya.png',
    'Тосты с авокадо': '11_Бутерброд_с_сыром.jpg',
    'Орехи': '28_Банановый_смузи.jpg',
    'Йогурт': '9_Творог_со_сметаной.jpg',
    'Фруктовый салат': '29_Салат_из_огурцов_и_помидоров.jpg',
    'Гренки': '32_Бутерброд_с_ветчиной.jpg',
    'Творожная запеканка': '30_Сырники.jpg',
    'Курица Терияки': '13_Куриное_филе_с_рисом.jpg',
    'Гуляш': '23_Гуляш_из_говядины_с_пюре.jpg',
    'Суп': '17_Куриный_суп.jpg',
    'Рыба': '27_Жаркое_из_свинины_с_картошкой.jpg',
    'Котлеты': '34_Котлеты_по-киевски.jpg',
    'Капуста': '27_Жаркое_из_свинины_с_картошкой.jpg',
    'Картошка': '27_Жаркое_из_свинины_с_картошкой.jpg',
    'Картофель': '18_Картофельное_пюре_с_котлетой.jpg',
    'Рагу': '15_Макароны_по-флотски.jpg',
    'Лапша': '13_Куриное_филе_с_рисом.jpg',
    'Курица': '14_Плов_с_курицей.jpg',
    'Говядина': '23_Гуляш_из_говядины_с_пюре.jpg',
    'Свинина': '27_Жаркое_из_свинины_с_картошкой.jpg',
    'Смузи': '28_Банановый_смузи.jpg',
    'Творог': '9_Творог_со_сметаной.jpg',
    'Бутерброд': '11_Бутерброд_с_сыром.jpg',
    'Курица терияки': '13_Куриное_филе_с_рисом.jpg',
    'Паста Карбонара': 'Diplom_6.png',
}

DEFAULT_IMAGE = 'Diplom_6.png'


def assign_images_to_recipes(apps, schema_editor):
    """Assign image files to recipes based on recipe name matching."""
    Recipes = apps.get_model('mainapp', 'Recipes')
    
    recipes_without_image = Recipes.objects.filter(image__isnull=True) | Recipes.objects.filter(image='')
    
    assigned_count = 0
    for recipe in recipes_without_image:
        image_name = None
        
        # Try exact match first
        if recipe.name in IMAGE_MAP:
            image_name = IMAGE_MAP[recipe.name]
        else:
            # Try keyword matching
            for keyword, img in IMAGE_MAP.items():
                if keyword.lower() in recipe.name.lower():
                    image_name = img
                    break
        
        # Use default image if no match found
        if not image_name:
            image_name = DEFAULT_IMAGE
        
        recipe.image = f'recipes/{image_name}'
        recipe.save(update_fields=['image'])
        assigned_count += 1
    
    if assigned_count:
        print(f'  Assigned images to {assigned_count} recipes')


def reverse_func(apps, schema_editor):
    """Remove assigned images (set back to empty)."""
    Recipes = apps.get_model('mainapp', 'Recipes')
    for image_name in set(IMAGE_MAP.values()) | {DEFAULT_IMAGE}:
        Recipes.objects.filter(image=f'recipes/{image_name}').update(image='')


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_recipes_spoonacular_id'),
    ]

    operations = [
        migrations.RunPython(assign_images_to_recipes, reverse_func),
    ]
