# Generated by Django 6.0.3 on 2026-04-26
"""
Data migration: add 2 new recipes - "Курица терияки с рисом" and "Паста Карбонара"
"""

from django.db import migrations


def add_recipes(apps, schema_editor):
    """Add two new hot dish recipes to the database."""
    Recipes = apps.get_model('mainapp', 'Recipes')
    Kitchenname = apps.get_model('mainapp', 'Kitchenname')

    # Get existing kitchen entries (take first if duplicates exist)
    japanese_kitchen = Kitchenname.objects.filter(name='Японская').first()
    italian_kitchen = Kitchenname.objects.filter(name='Итальянская').first()

    # Create kitchens if they don't exist
    if not japanese_kitchen:
        japanese_kitchen = Kitchenname.objects.create(name='Японская')
    if not italian_kitchen:
        italian_kitchen = Kitchenname.objects.create(name='Итальянская')

    # Recipe 1: Курица терияки с рисом
    Recipes.objects.create(
        name='Курица терияки с рисом',
        description='Нежные кусочки куриного филе, обжаренные в густом сладко-солёном соусе терияки с чесноком и имбирём. Подаются на подушке из рассыпчатого риса. Блюдо готовится быстро, а соус терияки придаёт курице золотистую корочку и насыщенный вкус. Идеально подходит для обеда или ужина.',
        calories=420,
        image='',
        KitchennameId=japanese_kitchen,
        meal_type='dinner',
        goal_suitability='maintain',
        cost_level=2,
        spoonacular_id=None,
    )

    # Recipe 2: Паста Карбонара
    Recipes.objects.create(
        name='Паста Карбонара',
        description='Классическая итальянская паста с соусом из яичных желтков, сыра пармезан, бекона и чёрного перца. Сливочный соус готовится без добавления сливок — нежную текстуру обеспечивают яйца и сыр. Спагетти отвариваются до состояния аль денте и смешиваются с горячей мясной смесью прямо в сковороде.',
        calories=530,
        image='',
        KitchennameId=italian_kitchen,
        meal_type='lunch',
        goal_suitability='gain',
        cost_level=2,
        spoonacular_id=None,
    )


def remove_recipes(apps, schema_editor):
    """Remove the two recipes added by this migration."""
    Recipes = apps.get_model('mainapp', 'Recipes')
    Recipes.objects.filter(name='Курица терияки с рисом').delete()
    Recipes.objects.filter(name='Паста Карбонара').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_assign_recipe_images'),
    ]

    operations = [
        migrations.RunPython(add_recipes, remove_recipes),
    ]
