# Generated by Django 6.0.3 on 2026-06-02
"""
Data migration: add more recipes for lose and maintain goals
"""

from django.db import migrations


def add_recipes(apps, schema_editor):
    """Add new recipes for weight loss and maintenance goals."""
    Recipes = apps.get_model('mainapp', 'Recipes')
    Kitchenname = apps.get_model('mainapp', 'Kitchenname')

    # Get or create kitchen entries
    russian_kitchen = Kitchenname.objects.filter(name='Русская').first()
    if not russian_kitchen:
        russian_kitchen = Kitchenname.objects.create(name='Русская')
    
    diet_kitchen = Kitchenname.objects.filter(name='Диетическая').first()
    if not diet_kitchen:
        diet_kitchen = Kitchenname.objects.create(name='Диетическая')
    
    mediterranean_kitchen = Kitchenname.objects.filter(name='Средиземноморская').first()
    if not mediterranean_kitchen:
        mediterranean_kitchen = Kitchenname.objects.create(name='Средиземноморская')

    # === Рецепты для ПОХУДЕНИЯ (lose) ===
    
    # 1. Запечённая куриная грудка с овощами
    Recipes.objects.create(
        name='Запечённая куриная грудка с овощами',
        description='Нежная куриная грудка, запечённая с кабачками, болгарским перцем и помидорами черри. Блюдо низкокалорийное, богато белком и витаминами. Готовится в духовке с минимальным количеством масла.',
        calories=220,
        image='',
        KitchennameId=diet_kitchen,
        meal_type='dinner',
        goal_suitability='lose',
        cost_level=1,
        spoonacular_id=None,
    )

    # 2. Овощной суп-пюре
    Recipes.objects.create(
        name='Овощной суп-пюре из брокколи',
        description='Лёгкий крем-суп из брокколи со спаржей и зелёным горошком. Насыщен витаминами и клетчаткой, идеально подходит для ужина при похудении. Подаётся с сухариками из цельнозернового хлеба.',
        calories=150,
        image='',
        KitchennameId=diet_kitchen,
        meal_type='lunch',
        goal_suitability='lose',
        cost_level=1,
        spoonacular_id=None,
    )

    # 3. Творожная запеканка без сахара
    Recipes.objects.create(
        name='Творожная запеканка с ягодами',
        description='Воздушная запеканка из нежирного творога с свежими ягодами (голубика, малина). Без добавления сахара — сладость придают ягоды и немного мёда. Отличный завтрак для тех, кто следит за фигурой.',
        calories=180,
        image='',
        KitchennameId=diet_kitchen,
        meal_type='breakfast',
        goal_suitability='lose',
        cost_level=2,
        spoonacular_id=None,
    )

    # 4. Салат с тунцом и овощами
    Recipes.objects.create(
        name='Салат с тунцом и свежими овощами',
        description='Свежий салат с тунцом в собственном соку, огурцом, помидором, красным луком и листьями салата. Заправляется лимонным соком и оливковым маслом. Богат белком и омега-3.',
        calories=190,
        image='',
        KitchennameId=mediterranean_kitchen,
        meal_type='lunch',
        goal_suitability='lose',
        cost_level=2,
        spoonacular_id=None,
    )

    # 5. Паровые котлеты из индейки
    Recipes.objects.create(
        name='Котлеты из индейки на пару',
        description='Нежные паровые котлеты из филе индейки с кабачком и луком. Готовятся без масла, сохраняют максимум пользы. Подаются с тушёными овощами или лёгким салатом.',
        calories=210,
        image='',
        KitchennameId=diet_kitchen,
        meal_type='dinner',
        goal_suitability='lose',
        cost_level=2,
        spoonacular_id=None,
    )

    # 6. Омлет с овощами
    Recipes.objects.create(
        name='Омлет с помидорами и шпинатом',
        description='Воздушный омлет из двух яиц с свежими помидорами, шпинатом и зеленью. Быстрый и полезный завтрак, богатый белком. Готовится за 10 минут.',
        calories=200,
        image='',
        KitchennameId=diet_kitchen,
        meal_type='breakfast',
        goal_suitability='lose',
        cost_level=1,
        spoonacular_id=None,
    )

    # === Рецепты для ПОДДЕРЖАНИЯ (maintain) ===

    # 7. Плов с курицей
    Recipes.objects.create(
        name='Плов с курицей',
        description='Ароматный плов с кусочками курицы, морковью, луком и рисом. Приготовлен с зиру и барбарисом. Сытное и вкусное блюдо для полноценного обеда.',
        calories=380,
        image='',
        KitchennameId=russian_kitchen,
        meal_type='lunch',
        goal_suitability='maintain',
        cost_level=2,
        spoonacular_id=None,
    )

    # 8. Бефстроганов с гречкой
    Recipes.objects.create(
        name='Бефстроганов с гречкой',
        description='Классический бефстроганов из говядины в сметанном соусе, подаётся с рассыпчатой гречкой. Насыщенное блюдо с богатым вкусом, идеально для обеда.',
        calories=400,
        image='',
        KitchennameId=russian_kitchen,
        meal_type='lunch',
        goal_suitability='maintain',
        cost_level=2,
        spoonacular_id=None,
    )

    # 9. Рыба запечённая с лимоном
    Recipes.objects.create(
        name='Рыба запечённая с лимоном и травами',
        description='Филе белой рыбы (треска или хек), запечённое с дольками лимона, розмарином и тимьяном. Нежное блюдо, богатое белком и омега-3 жирными кислотами.',
        calories=280,
        image='',
        KitchennameId=mediterranean_kitchen,
        meal_type='dinner',
        goal_suitability='maintain',
        cost_level=2,
        spoonacular_id=None,
    )

    # 10. Сырники с йогуртом
    Recipes.objects.create(
        name='Сырники с натуральным йогуртом',
        description='Домашние сырники из творога с минимальным количеством муки, подаются с натуральным йогуртом и свежими ягодами. Сытный и полезный завтрак.',
        calories=320,
        image='',
        KitchennameId=russian_kitchen,
        meal_type='breakfast',
        goal_suitability='maintain',
        cost_level=1,
        spoonacular_id=None,
    )

    # 11. Куриные наггетсы домашние
    Recipes.objects.create(
        name='Домашние куриные наггетсы',
        description='Кусочки куриной грудки в хрустящей панировке, запечённые в духовке. Более полезная альтернатива фастфуду. Подаются с овощным гарниром.',
        calories=300,
        image='',
        KitchennameId=russian_kitchen,
        meal_type='dinner',
        goal_suitability='maintain',
        cost_level=2,
        spoonacular_id=None,
    )

    # 12. Греческий салат
    Recipes.objects.create(
        name='Греческий салат с фетой',
        description='Свежий салат с помидорами, огурцами, болгарским перцем, маслинами и сыром фета. Заправляется оливковым маслом и орегано. Лёгкий и питательный гарнир или самостоятельное блюдо.',
        calories=250,
        image='',
        KitchennameId=mediterranean_kitchen,
        meal_type='snack',
        goal_suitability='maintain',
        cost_level=2,
        spoonacular_id=None,
    )


def remove_recipes(apps, schema_editor):
    """Remove the recipes added by this migration."""
    Recipes = apps.get_model('mainapp', 'Recipes')
    recipe_names = [
        'Запечённая куриная грудка с овощами',
        'Овощной суп-пюре из брокколи',
        'Творожная запеканка с ягодами',
        'Салат с тунцом и свежими овощами',
        'Котлеты из индейки на пару',
        'Омлет с помидорами и шпинатом',
        'Плов с курицей',
        'Бефстроганов с гречкой',
        'Рыба запечённая с лимоном и травами',
        'Сырники с натуральным йогуртом',
        'Домашние куриные наггетсы',
        'Греческий салат с фетой',
    ]
    for name in recipe_names:
        Recipes.objects.filter(name=name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_add_new_recipes'),
    ]

    operations = [
        migrations.RunPython(add_recipes, remove_recipes),
    ]
