# Generated by Django 6.0.3 on 2026-06-05
"""
Data migration: add premium recipes (steaks, lobsters, duck, etc.) for all meal types and goals
"""

from django.db import migrations


def add_recipes(apps, schema_editor):
    """Add premium recipes for all meal types and goals."""
    Recipes = apps.get_model('mainapp', 'Recipes')
    Kitchenname = apps.get_model('mainapp', 'Kitchenname')

    # Get or create kitchen entries
    french_kitchen = Kitchenname.objects.filter(name='Французская').first()
    if not french_kitchen:
        french_kitchen = Kitchenname.objects.create(name='Французская')
    
    american_kitchen = Kitchenname.objects.filter(name='Американская').first()
    if not american_kitchen:
        american_kitchen = Kitchenname.objects.create(name='Американская')
    
    mediterranean_kitchen = Kitchenname.objects.filter(name='Средиземноморская').first()
    if not mediterranean_kitchen:
        mediterranean_kitchen = Kitchenname.objects.create(name='Средиземноморская')
    
    italian_kitchen = Kitchenname.objects.filter(name='Итальянская').first()
    if not italian_kitchen:
        italian_kitchen = Kitchenname.objects.create(name='Итальянская')
    
    russian_kitchen = Kitchenname.objects.filter(name='Русская').first()
    if not russian_kitchen:
        russian_kitchen = Kitchenname.objects.create(name='Русская')

    # === ПРЕМИУМ РЕЦЕПТЫ ===

    # --- ЗАВТРАКИ (breakfast) ---

    # 1. Омлет с лобстером и трюфельным маслом (Premium breakfast for gain)
    Recipes.objects.create(
        name='Омлет с лобстером и трюфельным маслом',
        description='Нежный французский омлет с мясом лобстера, посыпанный свежим укропом и сбрызнутый трюфельным маслом. Подается с тостами из заквасочного хлеба. Роскошный завтрак для особого случая.',
        calories=450,
        image='',
        KitchennameId=french_kitchen,
        meal_type='breakfast',
        goal_suitability='gain',
        cost_level=3,
        spoonacular_id=None,
    )

    # 2. Блинчики с икрой и сливочным маслом (Premium breakfast for maintain)
    Recipes.objects.create(
        name='Блинчики с красной икрой',
        description='Тонкие ажурные блинчики с красной икрой, сливочным маслом и свежей зеленью. Классика русской кухни для особого завтрака. Подается с горячим чаем или кофе.',
        calories=380,
        image='',
        KitchennameId=russian_kitchen,
        meal_type='breakfast',
        goal_suitability='maintain',
        cost_level=3,
        spoonacular_id=None,
    )

    # 3. Тосты с авокадо и слабосоленым лососем (Premium breakfast for lose)
    Recipes.objects.create(
        name='Тосты с авокадо и лососем',
        description='Хрустящий тост из цельнозернового хлеба с кремовым авокадо, ломтиками слабосоленого лососем и каплей лимонного сока. Богат белком и полезными жирами.',
        calories=320,
        image='',
        KitchennameId=mediterranean_kitchen,
        meal_type='breakfast',
        goal_suitability='lose',
        cost_level=3,
        spoonacular_id=None,
    )

    # --- ОБЕДЫ (lunch) ---

    # 4. Стейк из мраморной говядины Рибай (Premium lunch for gain)
    Recipes.objects.create(
        name='Стейк Рибай из мраморной говядины',
        description='Сочный стейк из мраморной говядины зернового откорма, обжаренный до золотистой корочки с розмарином и чесноком. Подается с запечённым картофелем и овощами гриль. Идеален для набора массы.',
        calories=650,
        image='',
        KitchennameId=american_kitchen,
        meal_type='lunch',
        goal_suitability='gain',
        cost_level=3,
        spoonacular_id=None,
    )

    # 5. Утка по-пекински (Premium lunch for maintain)
    Recipes.objects.create(
        name='Утка по-пекински',
        description='Классическое китайское блюдо — утка с хрустящей корочкой, подаётся с тонкими блинчиками, огурцом, зелёным луком и соусом хойсин. Роскошный обед для особого случая.',
        calories=520,
        image='',
        KitchennameId=Kitchenname.objects.create(name='Китайская') if not Kitchenname.objects.filter(name='Китайская').exists() else Kitchenname.objects.filter(name='Китайская').first(),
        meal_type='lunch',
        goal_suitability='maintain',
        cost_level=3,
        spoonacular_id=None,
    )

    # 6. Стейк из тунца с семенами кунжута (Premium lunch for lose)
    Recipes.objects.create(
        name='Стейк из тунца с кунжутом',
        description='Стейк из свежего тунца, обжаренный до розовой середины с кунжутной корочкой. Подается с салатом из водорослей и соевым соусом. Богат белком и омега-3.',
        calories=290,
        image='',
        KitchennameId=Kitchenname.objects.create(name='Японская') if not Kitchenname.objects.filter(name='Японская').exists() else Kitchenname.objects.filter(name='Японская').first(),
        meal_type='lunch',
        goal_suitability='lose',
        cost_level=3,
        spoonacular_id=None,
    )

    # --- УЖИНЫ (dinner) ---

    # 7. Стейк из лосося с спаржей (Premium dinner for gain)
    Recipes.objects.create(
        name='Стейк из лосося со спаржей',
        description='Сочный стейк из атлантического лосося, запечённый с лимоном и укропом, подается с бланшированной спаржей и сливочным соусом. Богат белком и омега-3.',
        calories=580,
        image='',
        KitchennameId=mediterranean_kitchen,
        meal_type='dinner',
        goal_suitability='gain',
        cost_level=3,
        spoonacular_id=None,
    )

    # 8. Филе миньон с трюфельным пюре (Premium dinner for maintain)
    Recipes.objects.create(
        name='Филе миньон с трюфельным пюре',
        description='Нежное филе миньон из говяжьей вырезки, обжаренное до средней прожарки, подается с кремовым картофельным пюре с трюфельным маслом и красным винным соусом. Изысканный ужин.',
        calories=540,
        image='',
        KitchennameId=french_kitchen,
        meal_type='dinner',
        goal_suitability='maintain',
        cost_level=3,
        spoonacular_id=None,
    )

    # 9. Креветки тигровые в чесночном масле (Premium dinner for lose)
    Recipes.objects.create(
        name='Тигровые креветки в чесночном масле',
        description='Крупные тигровые креветки, обжаренные в сливочном масле с чесноком, петрушкой и лимоном. Подаются с лёгким салатом. Низкокалорийное и белковое блюдо.',
        calories=280,
        image='',
        KitchennameId=mediterranean_kitchen,
        meal_type='dinner',
        goal_suitability='lose',
        cost_level=3,
        spoonacular_id=None,
    )

    # --- ПЕРЕКУСЫ (snack) ---

    # 10. Капрезе с моцареллой буффало (Premium snack for maintain)
    Recipes.objects.create(
        name='Капрезе с моцареллой буффало',
        description='Итальянская закуска из свежих помидоров, моцареллы буффало, свежего базилика и бальзамического крема. Подается с хрустящим багетом.',
        calories=310,
        image='',
        KitchennameId=italian_kitchen,
        meal_type='snack',
        goal_suitability='maintain',
        cost_level=3,
        spoonacular_id=None,
    )

    # 11. Сашими из лосося и тунца (Premium snack for lose)
    Recipes.objects.create(
        name='Сашими из лосося и тунца',
        description='Свежайшие ломтики лосося и тунца, подаются с васаби, маринованным имбирём и соевым соусом. Легкий и белковый перекус.',
        calories=220,
        image='',
        KitchennameId=Kitchenname.objects.filter(name='Японская').first(),
        meal_type='snack',
        goal_suitability='lose',
        cost_level=3,
        spoonacular_id=None,
    )

    # 12. Кальмары гриль с чили (Premium snack for gain)
    Recipes.objects.create(
        name='Кальмары гриль с чили',
        description='Крупные кольца кальмара, обжаренные на гриле с перцем чили, чесноком и лаймом. Подается с соусом из йогурта. Белковый перекус для набора массы.',
        calories=340,
        image='',
        KitchennameId=mediterranean_kitchen,
        meal_type='snack',
        goal_suitability='gain',
        cost_level=3,
        spoonacular_id=None,
    )


def remove_recipes(apps, schema_editor):
    """Remove the premium recipes added by this migration."""
    Recipes = apps.get_model('mainapp', 'Recipes')
    recipe_names = [
        'Омлет с лобстером и трюфельным маслом',
        'Блинчики с красной икрой',
        'Тосты с авокадо и лососем',
        'Стейк Рибай из мраморной говядины',
        'Утка по-пекински',
        'Стейк из тунца с кунжутом',
        'Стейк из лосося со спаржей',
        'Филе миньон с трюфельным пюре',
        'Тигровые креветки в чесночном масле',
        'Капрезе с моцареллой буффало',
        'Сашими из лосося и тунца',
        'Кальмары гриль с чили',
    ]
    for name in recipe_names:
        Recipes.objects.filter(name=name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_add_more_diet_recipes'),
    ]

    operations = [
        migrations.RunPython(add_recipes, remove_recipes),
    ]
